improve teardown and logging

diff --git a/write_os_to_pi b/write_os_to_pi
--- a/write_os_to_pi
+++ b/write_os_to_pi
@@ -40,6 +40,8 @@ printr() {
         color="1;32m"
     elif [[ $2 == "error" ]]; then
         color="1;31m"
+    elif [[ $2 == "warning" ]]; then
+        color="1;33m"
     fi
 
     echo -e "\033[$color$1\033[0m"
@@ -331,9 +333,25 @@ cleanup() {
     LOGS+=("i Unmounting boot")
     local error=$(sudo umount boot 2>&1)
 
+    
+
     if ((  $? )); then
-        LOGS+=("e Could unmount boot: $error")
+        notMounted=0
+        [[ ${error:(-7)} == "mounted" ]] && notMounted=1
+        if (( $notMounted )); then
+            LOGS+=("w Could not unmount boot: $error")
+            LOGS+=("i Removing boot")
+
+            error=$(rm -rf boot 2>&1)
+
+            if ((  $? )); then
+                LOGS+=("e Could not remove boot: $error")
+            fi
+        else
+            LOGS+=("e Could not unmount boot: $error")
+        fi
     else
+        LOGS+=("i Removing boot")
         error=$(rm -rf boot 2>&1)
 
         if ((  $? )); then
@@ -345,8 +363,20 @@ cleanup() {
     error=$(sudo umount rootfs 2>&1)
 
     if ((  $? )); then
-        LOGS+=("e Could unmount boot: $error")
+        notMounted=0
+        [[ ${error:(-7)} == "mounted" ]] && notMounted=1
+        if (( $notMounted )); then
+            LOGS+=("w Could not unmount rootfs: $error")
+            
+            LOGS+=("i Removing rootfs")
+            error=$(rm -rf rootfs 2>&1)
+
+            if ((  $? )); then
+                LOGS+=("e Could not remove rootfs: $error")
+            fi
+        fi
     else
+        LOGS+=("i Removing rootfs")
         error=$(rm -rf rootfs 2>&1)
 
         if ((  $? )); then
@@ -354,10 +384,11 @@ cleanup() {
         fi
     fi
 
+    LOGS+=("i Removing $IMAGE")
     error=$(rm $IMAGE 2>&1)
 
      if ((  $? )); then
-        LOGS+=("e Could not remove boot: $IMAGE")
+        LOGS+=("e Could not remove $IMAGE: $error")
     fi
 }
 
@@ -451,6 +482,10 @@ writeLogTofile() {
         local prefix="[INFO]"
         if [[ ${log:0:1} == "e" ]]; then
             prefix="[ERROR]"
+        elif [[ ${log:0:1} == "w" ]]; then
+            prefix="[ERROR]"
+        elif [[ ${log:0:1} == "w" ]]; then
+            prefix="[WARNING]"
         fi
 
         echo "$(date) $prefix ${log:2}" >> log.txt
@@ -471,6 +506,8 @@ showLogs() {
             local color="info"
             if [[ ${log:0:1} == "e" ]]; then
                 color="error"
+            elif [[ ${log:0:1} == "w" ]]; then
+                color="warning"
             fi
 
             printr "  ${log:2}" "$color" log
