Added cgroup enabling

diff --git a/write_os_to_pi b/write_os_to_pi
--- a/write_os_to_pi
+++ b/write_os_to_pi
@@ -91,6 +91,14 @@ toggleIncrementalHostnameStatus() {
     fi
 }
 
+toggleCgroups() {
+    if [[ $CGROUP_STATUS == ON ]]; then
+        CGROUP_STATUS=OFF
+    else
+        CGROUP_STATUS=ON
+    fi
+}
+
 showAvailableDisksOptions() {
     if isAvailable; then
         printr "  Select Device(s)" normal menu
@@ -114,6 +122,7 @@ showGenericMenu() {
 
     fi  
 
+    printr "    g. Enable cgroups" normal menu
     printr "    c. Cleanup" normal menu
     printr "    q. Quit" normal menu
 }
@@ -183,10 +192,11 @@ isSingleSelected() {
 }
 
 unpackArchive() {
+    local error=0
     if [[ ! -e $IMAGE ]]; then
         if [[ -e $XZ_IMAGE ]]; then
             LOGS+=("i Unpacking $XZ_IMAGE")
-            local error=$(xz -dk  $XZ_IMAGE 2>&1)
+            error=$(xz -dk  $XZ_IMAGE 2>&1)
 
             if [[ $? != 0 ]]; then
                 LOGS+=("e Could not unpack $XZ_IMAGE: $error")
@@ -200,7 +210,9 @@ unpackArchive() {
 
 writeImageTodisk() {
     LOGS+=("i Writing $IMAGE to $1")
-    local error=$(sudo dd if=$IMAGE of=$1 bs=16M 2>&1)
+    local error=0
+
+    error=$(sudo dd if=$IMAGE of=$1 bs=16M 2>&1)
 
     if [[ $? != 0 ]]; then
         LOGS+=("e Could not write $IMAGE to $1: $error")
@@ -209,9 +221,10 @@ writeImageTodisk() {
 }
 
 unmountAllDevicePartitions() {
+    local error=0
    for i in $(lsblk -l | grep ${1:(-3)}[1-9] | awk '{print $1}'); do
         LOGS+=("i Unmounting /dev/$i");
-        local error=$(sudo umount /dev/$i 2>&1)
+        error=$(sudo umount /dev/$i 2>&1)
 
         if [[ $? != 0 ]]; then
             LOGS+=("e Could not unmount /dev/$i: $error")
@@ -221,8 +234,10 @@ unmountAllDevicePartitions() {
 
 createMountPoints() {
     LOGS+=("i Creating mount points");
+    local error=0
+
     if [[ ! -e boot ]]; then
-        local error=$(mkdir boot 2>&1)
+        error=$(mkdir boot 2>&1)
 
         if [[ $? != 0 ]]; then
             LOGS+=("e Could not create mount point boot: $error")
@@ -230,7 +245,7 @@ createMountPoints() {
     fi
 
     if [[ ! -e rootfs ]]; then
-        local error=$(mkdir rootfs 2>&1)
+        error=$(mkdir rootfs 2>&1)
 
         if [[ $? != 0 ]]; then
             LOGS+=("e Could not create mount point rootfs: $error")
@@ -240,7 +255,9 @@ createMountPoints() {
 
 mountPartitions() {
     LOGS+=("i Mouting $1");
-    local error=$(sudo mount -t vfat "$1"1 boot 2>&1)
+    local error=0
+
+    error=$(sudo mount -t vfat "$1"1 boot 2>&1)
 
     if [[ $? != 0 ]]; then
         LOGS+=("e Could not mount $1 on boot: $error")
@@ -255,9 +272,11 @@ mountPartitions() {
 
 generateSSHKeygen() {
     LOGS+=("i Checking local SSH keys");
+    local error=0
+
     if [[ ! -e $HOME/.ssh/id_rsa.pub ]];then
         LOGS+=("i Generating local SSH keys");
-        local error=$(ssh-keygen -b 4096 -t rsa -q -N "" 2>&1)
+        error=$(ssh-keygen -b 4096 -t rsa -q -N "" 2>&1)
 
         if [[ $? != 0 ]]; then
         LOGS+=("e Could not generate SSH private and public keys: $error")
@@ -266,8 +285,10 @@ generateSSHKeygen() {
 }
 
 enableSSH() {
+    local error=0
+
     LOGS+=("i Enabling SSH");
-    local error=$(sudo touch boot/ssh 2>&1)
+    error=$(sudo touch boot/ssh 2>&1)
 
     if [[ $? != 0 ]]; then
         LOGS+=("e Could not enable SSH: $error")
@@ -276,7 +297,7 @@ enableSSH() {
 
 addHostname() {
     LOGS+=("i Adding hostname $1");
-    local error=$(sudo sed -i "s/raspberrypi/$1/" rootfs/etc/hostname 2>&1)
+    error=$(sudo sed -i "s/raspberrypi/$1/" rootfs/etc/hostname 2>&1)
     if [[ $? != 0 ]]; then
         LOGS+=("e Could not enable SSH: $error")
     fi
@@ -284,9 +305,10 @@ addHostname() {
 
 copyPublicKey() {
     LOGS+=("i writing your public key");
+    local error=0
 
     if [[ ! -e rootfs/home/pi/.ssh ]]; then
-        local error=$(sudo mkdir -m 700 rootfs/home/pi/.ssh 2>&1)
+        error=$(sudo mkdir -m 700 rootfs/home/pi/.ssh 2>&1)
 
         if [[ $? != 0 ]]; then
             LOGS+=("e Could not create .ssh directory: $error")
@@ -294,7 +316,7 @@ copyPublicKey() {
     fi
 
     if [[ -e rootfs/home/pi/.ssh ]]; then
-        local error=$(sudo cp ~/.ssh/id_rsa.pub rootfs/home/pi/.ssh/authorized_keys 2>&1)
+        error=$(sudo cp ~/.ssh/id_rsa.pub rootfs/home/pi/.ssh/authorized_keys 2>&1)
 
         if [[ $? != 0 ]]; then
             LOGS+=("e Could not copy public key: $error")
@@ -307,19 +329,30 @@ copyPublicKey() {
         fi
     fi
 
-    local error=$(sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' rootfs/etc/ssh/sshd_config 2>&1)
+    error=$(sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' rootfs/etc/ssh/sshd_config 2>&1)
 
     if [[ $? != 0 ]]; then
             LOGS+=("e Could not set PasswordAuthentication field in rootfs/etc/ssh/sshd_config: $error")
     fi
 }
 
+enableCgroups() {
+    LOGS+=("i Enabling cgroups");
+    local error=0
+    error=$(sudo sed -i "s/rootwait/rootwait cgroup_memory=1 cgroup_enable=memory/" boot/cmdline.txt 2>&1)
+
+    if [[ $? != 0 ]]; then
+        LOGS+=("e Could not enable cgroups: $error")
+    fi
+}
+
 unmountEjectDevice() {
     LOGS+=("i Unmounting and ejecting device $1")
     unmountAllDevicePartitions $1
+    local error=0
 
     LOGS+=("i Ejecting device $1")
-    local error=$(sudo eject $1 2>&1)
+    error=$(sudo eject $1 2>&1)
 
     if [[ $? != 0 ]]; then
             LOGS+=("e Could not eject $1: $error")
@@ -442,6 +475,7 @@ handleChoice() {
                     enableSSH &&
                     addHostname $HOSTNAME_PREFIX$count &&
                     copyPublicKey &&
+                    enableCgroups &&
                     unmountEjectDevice $deviceKey
                     count=$((count+1))
 
